"""Tab 8 · Case Library (Experiment 8): documented AI incidents, analysed by ActAudit.

Case data lives in data/cases/cases.json (documented by cases.schema.json) and is
validated strictly here. Each case's neutral system description is recorded as a
fixture through the normal pipeline (scripts/record_fixtures.py --set cases), so the
tier shown is ActAudit's own reading of the description, not a verdict on the incident.

"Would the AI Act have caught this?" is generated by fixed rules from ActAudit's tier,
rule and extracted facts, and always notes that the Act is not retroactive.
"""
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from rules import RiskTier
from schema import ExtractedFacts

CASES_FILE = Path(__file__).resolve().parent.parent / "data" / "cases" / "cases.json"
MIN_WORDS, MAX_WORDS = 100, 150
ENTRY_INTO_FORCE = "2024-08"  # Art. 113: 20th day after OJ publication (12 July 2024) = 1 Aug 2024
REQUIRED = {"id", "title", "date", "jurisdiction", "fixture", "system_description", "what_happened",
            "harm", "what_followed", "sources", "unverified"}
SOURCE_KEYS = {"title", "publisher", "url", "accessed"}


class CaseDataError(ValueError):
    """cases.json is malformed."""


@dataclass(frozen=True)
class Source:
    title: str
    publisher: str
    url: str
    accessed: str


@dataclass(frozen=True)
class Case:
    id: str
    title: str
    date: str  # YYYY-MM when the incident became public
    jurisdiction: str
    fixture: str
    system_description: str
    what_happened: str
    harm: str
    what_followed: str
    sources: tuple[Source, ...]
    unverified: tuple[str, ...]

    @property
    def year(self) -> int:
        return int(self.date[:4])


def _validate(raw: dict[str, Any]) -> Case:
    cid = raw.get("id", "?")
    if set(raw) != REQUIRED:
        raise CaseDataError(f"case {cid}: keys {sorted(set(raw) ^ REQUIRED)} missing or unknown")
    if not re.fullmatch(r"[a-z0-9_]+", raw["id"]):
        raise CaseDataError(f"case {cid}: id must be lower_snake_case")
    if not re.fullmatch(r"\d{4}-\d{2}", raw["date"]):
        raise CaseDataError(f"case {cid}: date must be YYYY-MM")
    if raw["fixture"] != f"text__case_{raw['id']}":
        raise CaseDataError(f"case {cid}: fixture must be text__case_{raw['id']}")
    words = len(raw["system_description"].split())
    if not MIN_WORDS <= words <= MAX_WORDS:
        raise CaseDataError(f"case {cid}: system_description has {words} words ({MIN_WORDS}-{MAX_WORDS})")
    for key in ("title", "jurisdiction", "what_happened", "harm", "what_followed"):
        if not isinstance(raw[key], str) or not raw[key].strip():
            raise CaseDataError(f"case {cid}: {key} must be non-empty text")
    sources = raw["sources"]
    if not isinstance(sources, list) or len(sources) < 2:
        raise CaseDataError(f"case {cid}: at least two sources are required")
    for s in sources:
        if set(s) != SOURCE_KEYS or not s["url"].startswith("https://"):
            raise CaseDataError(f"case {cid}: each source needs {sorted(SOURCE_KEYS)} and an https URL")
    if not isinstance(raw["unverified"], list) or not all(isinstance(u, str) for u in raw["unverified"]):
        raise CaseDataError(f"case {cid}: unverified must be a list of strings")
    return Case(**{**raw, "sources": tuple(Source(**s) for s in sources),
                   "unverified": tuple(raw["unverified"])})


def load_cases(path: Path = CASES_FILE) -> list[Case]:
    data = json.loads(path.read_text())
    cases = [_validate(c) for c in data["cases"]]
    ids = [c.id for c in cases]
    if len(ids) != len(set(ids)):
        raise CaseDataError("case ids must be unique")
    return cases


# --- "Would the AI Act have caught this?" (rule-generated) ------------------------------------

def would_act_catch(case: Case, tier: RiskTier, provision: str, facts: ExtractedFacts) -> str:
    if tier == RiskTier.OUT_OF_SCOPE:
        verdict = ("No — ActAudit reads it as exclusively military, defence or national-security "
                   "use, which the AI Act excludes (Art. 2(3)).")
    elif tier == RiskTier.PROHIBITED:
        verdict = (f"Yes — ActAudit places it under a prohibited practice ({provision}), so it "
                   "could not be placed on the EU market or used in the EU.")
    elif tier == RiskTier.HIGH_RISK:
        verdict = (f"Partly — as a high-risk system ({provision}) it would need risk management "
                   "(Art. 9), data governance and bias examination (Art. 10), human oversight "
                   "(Art. 14) and accuracy and robustness testing (Art. 15) before use. These "
                   "target the kind of failure seen here, but the Act does not ban the system.")
    else:
        verdict = (f"Probably not — ActAudit finds no prohibited or high-risk category "
                   f"({tier.value}), so at most transparency duties would apply.")
    extras = []
    if facts.generates_synthetic_media or facts.impersonation_capable:
        extras.append("Art. 50 would require marking synthetic output and disclosing deep fakes, "
                      "but those duties don't stop someone using the tool to commit fraud, which "
                      "is already a crime.")
    if facts.biometric_use and tier != RiskTier.PROHIBITED:
        extras.append("ActAudit's rules don't model Art. 5(1)(e), which prohibits building "
                      "facial-recognition databases by untargeted scraping of facial images from "
                      "the internet or CCTV footage; a system built that way would be prohibited.")
    timing = ("The Act is not retroactive: it entered into force on 1 August 2024, with most "
              "obligations applying from 2 August 2026")
    timing += (f", and this case ({case.date[:4]}) predates it." if case.date < ENTRY_INTO_FORCE
               else ".")
    return " ".join([verdict, *extras, timing])
