"""Tab 2 · Dataset Bias (Experiment 2): representation, reference shares,
intersectional counts, missingness and label base rates by group, plus a findings
summary generated by fixed rules from those numbers (no LLM).

Also loads datasets for Tabs 2, 4 and 5: a capped, sampled CSV upload or a bundled
demo from data/datasets.json (built by scripts/make_demo_datasets.py).
"""
import io
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pandas as pd

from analysis import config

DATA_DIR = Path(__file__).resolve().parent.parent / "data"
MISSING_GROUP = "(missing)"

# EU AI Act Art. 10 (data and data governance) — verified against the Official Journal
# text of Regulation (EU) 2024/1689: 10(2)(f) examination for possible biases, 10(2)(g)
# measures to detect, prevent and mitigate them, 10(3) representative data sets.
ART10_NOTE = (
    "This system is classified High-Risk, so its training, validation and testing data "
    "must be examined for possible biases, with measures to detect, prevent and mitigate "
    "them (EU AI Act Art. 10(2)(f)–(g)), and must be relevant and sufficiently "
    "representative, including for the groups the system is used on (Art. 10(3)). The "
    "checks below are the kind of examination Art. 10 asks for; they do not by themselves "
    "show compliance."
)
ART10_CITATION = "EU AI Act Art. 10(2)(f)–(g), 10(3)"
ART10_VERIFIED = True


class DatasetError(ValueError):
    """A dataset can't be used. `str(err)` is a friendly, user-facing message."""


@dataclass(frozen=True)
class LoadedDataset:
    df: pd.DataFrame
    rows_original: int
    sampled: bool


# --- Loading -------------------------------------------------------------------------

def load_csv(data: bytes, max_mb: float | None = None, row_cap: int | None = None,
             seed: int | None = None) -> LoadedDataset:
    """Parse an uploaded CSV, enforcing the size cap and sampling to the row cap."""
    max_mb = config.value("MAX_UPLOAD_MB") if max_mb is None else max_mb
    row_cap = int(config.value("ROW_CAP") if row_cap is None else row_cap)
    seed = int(config.value("SAMPLE_SEED") if seed is None else seed)
    if len(data) > max_mb * 1024 * 1024:
        raise DatasetError(f"The file is {len(data) / 1024 / 1024:.1f} MB; the limit is "
                           f"{max_mb:g} MB.")
    try:
        df = pd.read_csv(io.BytesIO(data), low_memory=False)
    except UnicodeDecodeError:
        raise DatasetError("The file isn't UTF-8 text. Save it as a UTF-8 CSV and try again.") from None
    except (pd.errors.ParserError, pd.errors.EmptyDataError, ValueError) as exc:
        raise DatasetError(f"The file couldn't be read as a CSV ({type(exc).__name__}).") from None
    if df.empty or df.shape[1] < 2:
        raise DatasetError("The CSV needs at least two columns and one row of data.")
    df.columns = [str(c).strip() or f"column_{i}" for i, c in enumerate(df.columns)]
    rows = len(df)
    if rows > row_cap:
        df = df.sample(n=row_cap, random_state=seed).reset_index(drop=True)
    return LoadedDataset(df, rows, rows > row_cap)


def demo_datasets() -> list[dict[str, Any]]:
    """The bundled demo datasets' manifest entries (data/datasets.json)."""
    path = DATA_DIR / "datasets.json"
    if not path.exists():
        return []
    return json.loads(path.read_text())["datasets"]


def load_demo(dataset_id: str) -> tuple[LoadedDataset, dict[str, Any]]:
    meta = next((d for d in demo_datasets() if d["id"] == dataset_id), None)
    if meta is None:
        raise DatasetError(f"There is no demo dataset called {dataset_id!r}.")
    df = pd.read_csv(DATA_DIR / meta["file"], low_memory=False)
    return LoadedDataset(df, len(df), False), meta


def group_column_candidates(df: pd.DataFrame, max_categories: int | None = None) -> list[str]:
    """Columns usable as a protected attribute: 2 to max_categories distinct values."""
    limit = int(config.value("MAX_CATEGORIES") if max_categories is None else max_categories)
    return [c for c in df.columns if 2 <= df[c].nunique(dropna=True) <= limit]


def _groups(series: pd.Series) -> pd.Series:
    return series.astype("object").where(series.notna(), MISSING_GROUP).astype(str)


# --- Representation ----------------------------------------------------------------------

@dataclass(frozen=True)
class RepresentationResult:
    attribute: str
    table: pd.DataFrame  # group, count, share, below_min_share
    imbalance_ratio: float  # largest / smallest group (missing values excluded)
    imbalanced: bool
    missing: int  # rows with no value for the attribute


def representation(df: pd.DataFrame, attribute: str, min_share: float | None = None,
                   imbalance_limit: float | None = None) -> RepresentationResult:
    min_share = config.value("MIN_GROUP_SHARE") if min_share is None else min_share
    imbalance_limit = config.value("IMBALANCE_RATIO") if imbalance_limit is None else imbalance_limit
    values = df[attribute].dropna().astype(str)
    counts = values.value_counts()
    table = pd.DataFrame({"group": counts.index, "count": counts.values})
    table["share"] = table["count"] / table["count"].sum()
    table["below_min_share"] = table["share"] < min_share
    ratio = float(counts.max() / counts.min()) if len(counts) >= 2 else 1.0
    return RepresentationResult(attribute, table.reset_index(drop=True), ratio,
                                ratio > imbalance_limit, int(df[attribute].isna().sum()))


def reference_comparison(rep: RepresentationResult, expected: dict[str, float],
                         under: float | None = None, over: float | None = None) -> pd.DataFrame:
    """Observed vs expected population shares. Expected shares are normalised to sum
    to 1 over the groups given; groups without an expected share are left out."""
    under = config.value("REF_UNDER") if under is None else under
    over = config.value("REF_OVER") if over is None else over
    expected = {g: float(v) for g, v in expected.items() if v is not None and float(v) > 0}
    total = sum(expected.values())
    rows = []
    for group, share in expected.items():
        exp = share / total
        observed = float(rep.table.loc[rep.table["group"] == group, "share"].sum())
        ratio = observed / exp
        status = ("under-represented" if ratio < under else
                  "over-represented" if ratio > over else "in line")
        rows.append({"group": group, "observed_share": observed, "expected_share": exp,
                     "ratio": ratio, "status": status})
    return pd.DataFrame(rows, columns=["group", "observed_share", "expected_share", "ratio", "status"])


# --- Intersectional counts ------------------------------------------------------------

@dataclass(frozen=True)
class IntersectionResult:
    a: str
    b: str
    table: pd.DataFrame  # a-value, b-value, count, small
    small_cells: int
    empty_cells: int  # combinations that never occur


def intersectional_counts(df: pd.DataFrame, a: str, b: str,
                          small_cell: int | None = None) -> IntersectionResult:
    small_cell = int(config.value("SMALL_CELL") if small_cell is None else small_cell)
    ga, gb = _groups(df[a]), _groups(df[b])
    counts = pd.crosstab(ga, gb)
    long = counts.stack().rename("count").reset_index()
    long.columns = [a, b, "count"]
    long["small"] = long["count"] < small_cell
    return IntersectionResult(a, b, long, int((long["count"].between(1, small_cell - 1)).sum()),
                              int((long["count"] == 0).sum()))


# --- Missingness by group ----------------------------------------------------------------

def missingness_by_group(df: pd.DataFrame, attribute: str,
                         gap: float | None = None) -> pd.DataFrame:
    """Missing-value rate of every other column, per group of `attribute`.

    Only columns with at least one missing value are listed. `gap` is the difference
    between the highest and lowest group rate; above the threshold it is flagged.
    """
    gap_limit = config.value("MISSINGNESS_GAP") if gap is None else gap
    groups = _groups(df[attribute])
    rows = []
    for column in df.columns:
        if column == attribute or not df[column].isna().any():
            continue
        rates = df[column].isna().groupby(groups).mean()
        row = {"column": column, "overall": float(df[column].isna().mean())}
        row.update({f"missing in {g}": float(r) for g, r in rates.items()})
        row["gap"] = float(rates.max() - rates.min())
        row["flagged"] = row["gap"] > gap_limit
        rows.append(row)
    table = pd.DataFrame(rows)
    if table.empty:
        return pd.DataFrame(columns=["column", "overall", "gap", "flagged"])
    return table.sort_values("gap", ascending=False).reset_index(drop=True)


# --- Label base rates --------------------------------------------------------------------

@dataclass(frozen=True)
class BaseRateResult:
    attribute: str
    label: str
    positive: Any
    table: pd.DataFrame  # group, count, positives, base_rate
    gap: float  # highest - lowest base rate
    flagged: bool


def label_base_rates(df: pd.DataFrame, attribute: str, label: str, positive: Any,
                     gap: float | None = None) -> BaseRateResult:
    gap_limit = config.value("BASE_RATE_GAP") if gap is None else gap
    data = df[[attribute, label]].dropna()
    groups = data[attribute].astype(str)
    is_pos = data[label] == positive
    table = pd.DataFrame({
        "count": groups.value_counts(),
        "positives": is_pos.groupby(groups).sum(),
    }).fillna(0).astype(int).rename_axis("group").reset_index()
    table["base_rate"] = table["positives"] / table["count"]
    table = table.sort_values("base_rate", ascending=False).reset_index(drop=True)
    spread = float(table["base_rate"].max() - table["base_rate"].min()) if len(table) else 0.0
    return BaseRateResult(attribute, label, positive, table, spread, spread > gap_limit)


# --- Findings (rule-generated text; no LLM) -----------------------------------------------

def _pct(x: float) -> str:
    return f"{x:.1%}"


def findings(rep: RepresentationResult,
             reference: pd.DataFrame | None = None,
             intersection: IntersectionResult | None = None,
             missing: pd.DataFrame | None = None,
             base: BaseRateResult | None = None) -> list[str]:
    """Plain-language findings, each produced by a fixed rule from the numbers."""
    out = []
    low = rep.table[rep.table["below_min_share"]]
    if not low.empty:
        groups = ", ".join(f"{g} ({_pct(s)})" for g, s in zip(low["group"], low["share"]))
        out.append(f"Under-represented in '{rep.attribute}': {groups} — below the "
                   f"{_pct(config.value('MIN_GROUP_SHARE'))} minimum share.")
    if rep.imbalanced:
        out.append(f"'{rep.attribute}' is imbalanced: the largest group is "
                   f"{rep.imbalance_ratio:.1f}× the smallest (threshold "
                   f"{config.value('IMBALANCE_RATIO'):g}×).")
    elif low.empty:
        out.append(f"'{rep.attribute}' groups are reasonably balanced (largest ÷ smallest = "
                   f"{rep.imbalance_ratio:.1f}×, no group below "
                   f"{_pct(config.value('MIN_GROUP_SHARE'))}).")
    if rep.missing:
        out.append(f"{rep.missing:,} rows have no value for '{rep.attribute}', so they can't "
                   "be checked for bias on this attribute.")
    if reference is not None and not reference.empty:
        off = reference[reference["status"] != "in line"]
        for _, row in off.iterrows():
            out.append(f"Compared with the reference population, '{row['group']}' is "
                       f"{row['status']}: {_pct(row['observed_share'])} of the data vs "
                       f"{_pct(row['expected_share'])} expected.")
        if off.empty:
            out.append("Group shares are in line with the reference population you entered.")
    if intersection is not None and (intersection.small_cells or intersection.empty_cells):
        out.append(f"Across '{intersection.a}' × '{intersection.b}', {intersection.small_cells} "
                   f"combination(s) have fewer than {int(config.value('SMALL_CELL'))} rows and "
                   f"{intersection.empty_cells} never occur: results for those intersections "
                   "are unreliable or impossible.")
    if missing is not None and not missing.empty:
        flagged = missing[missing["flagged"]]
        if not flagged.empty:
            worst = flagged.iloc[0]
            out.append(f"Missing data differs between groups in {len(flagged)} column(s); the "
                       f"largest gap is '{worst['column']}' ({_pct(worst['gap'])} between the "
                       "highest and lowest group).")
    if base is not None and len(base.table) >= 2:
        hi, lo = base.table.iloc[0], base.table.iloc[-1]
        if base.flagged:
            out.append(f"The label '{base.label}' = {base.positive} is much more common for "
                       f"'{hi['group']}' ({_pct(hi['base_rate'])}) than for '{lo['group']}' "
                       f"({_pct(lo['base_rate'])}): a gap of {_pct(base.gap)}. A model trained "
                       "on it will learn this difference.")
        else:
            out.append(f"Base rates of '{base.label}' = {base.positive} are similar across groups "
                       f"(gap {_pct(base.gap)}).")
    return out
