"""Tab 3 · Synthetic Media (Experiment 3): capabilities, Art. 50 transparency duties,
a misuse-vulnerability matrix and a rule-generated ethical analysis."""
import pandas as pd
import streamlit as st

import pipeline
from ui.components import PROJECT_HEURISTIC_BADGE, md_escape, quote_evidence, require_analysis

sm = pipeline.synthetic_media
STATUS_BADGE = {
    sm.APPLIES: ":red-badge[:material/gavel: Applies]",
    sm.MAY_APPLY: ":orange-badge[:material/help: May apply]",
    sm.NOT_APPLICABLE: ":gray-badge[Does not apply]",
}
SCORE_BADGE = {sm.HIGH: ":red-badge[High]", sm.MEDIUM: ":orange-badge[Medium]", sm.LOW: ":green-badge[Low]"}


def _capabilities(facts) -> None:
    st.markdown("##### Capabilities")
    cols = st.columns(3)
    for col, cap in zip(cols, sm.capabilities(facts)):
        with col.container(border=True, height="stretch"):
            icon = ":material/check_circle:" if cap.present else ":material/remove_circle_outline:"
            st.markdown(f"{icon} **{cap.name}**")
            st.markdown(f"`{cap.field}` = `{md_escape(cap.value)}`")
            if cap.evidence:
                quote_evidence(cap.field, cap.evidence)
            elif cap.present:
                st.caption("No evidence snippet was quoted.")


def _obligations(facts) -> None:
    st.markdown("##### Transparency obligations (EU AI Act Art. 50)")
    for ob in sm.transparency_obligations(facts):
        with st.container(border=True):
            st.markdown(f"**{ob.provision}** · {ob.duty_holder} duty {STATUS_BADGE[ob.status]} "
                        ":blue-badge[citation verified]")
            st.markdown(ob.duty)
            st.caption(f"**Why:** {ob.reason}")
            if ob.documentation != "—":
                st.caption(f"**Documentation:** {ob.documentation}")
            st.caption(f"**Exceptions:** {ob.exceptions}")
    st.caption(f":material/info: {sm.OBLIGATIONS_NOTE}")


def _matrix(facts) -> None:
    st.markdown(f"##### Misuse vulnerability matrix {PROJECT_HEURISTIC_BADGE}")
    matrix = sm.misuse_matrix(facts)
    if not matrix.rows:
        st.success("No synthetic-media capability was extracted, so there is nothing to score.",
                   icon=":material/check_circle:")
    else:
        mark = {True: ":material/check: documented", False: ":material/close: not documented"}
        st.table({
            "Capability": [r.capability for r in matrix.rows],
            **{col: [mark[r.safeguards[i]] for r in matrix.rows] for i, col in enumerate(sm.SAFEGUARD_COLUMNS)},
            "Vulnerability": [SCORE_BADGE[r.score] for r in matrix.rows],
        }, hide_index=True, border="horizontal")
        st.markdown(f"**Overall misuse vulnerability:** {SCORE_BADGE[matrix.overall]} (the highest row)")
        st.caption(sm.SAFEGUARD_NOTE)
    with st.expander("Scoring table", icon=":material/rule:"):
        st.caption("Score by capability and number of distinct safeguard facts documented "
                   "(output marking; consent / identity checks / usage policy). A project "
                   "heuristic, not derived from a specific Act provision.")
        st.dataframe(pd.DataFrame(
            [(c, *scores) for c, scores in sm.MISUSE_SCORING.items()],
            columns=["Capability", "0 safeguards", "1 safeguard", "2 safeguards"]), hide_index=True)


def _ethics(facts) -> None:
    st.markdown("##### Ethical analysis")
    st.caption("Generated by fixed rules from the capabilities above — no LLM is involved.")
    for theme, sentence in sm.ethical_analysis(facts):
        st.markdown(f"- **{theme}.** {sentence}")


def render() -> None:
    result = require_analysis("t3", pipeline.EXAMPLE_SETS["synthetic_media"], source="Tab 3")
    if result is None:
        return
    facts = result.extraction.facts
    if result.schema_version < pipeline.SCHEMA_VERSION:
        st.warning("This result was recorded with an older schema, before the synthetic-media "
                   "facts existed, so they all show their defaults (false). Load one of the "
                   "Tab 3 examples or re-run the audit.", icon=":material/history_toggle_off:")
    _capabilities(facts)
    _obligations(facts)
    _matrix(facts)
    _ethics(facts)
